import type { NextPage } from "next";
import Head from "next/head";
import { useAppDispatch, useAppSelector } from "@lib/hooks";
import { increment, decrement, reset, getCount } from "@redux/counter";
import CounterDisplay from "@shards/CounterDisplay";
import Button from "@components/shards/Button";

const Home: NextPage = () => {
    const count = useAppSelector(getCount);
    const dispatch = useAppDispatch();

    return (
        <div className="flex flex-col justify-evenly items-center h-screen min-h-screen px-0 py-2">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <CounterDisplay value={count} />

            <div className="flex justify-evenly w-full">
                <Button
                    label="Increment"
                    onClick={() => dispatch(increment())}
                />
                <Button label="Reset" onClick={() => dispatch(reset())} />
                <Button
                    label="Decrement"
                    onClick={() => dispatch(decrement())}
                />
            </div>
        </div>
    );
};

export default Home;
